pipeline {
    agent {
        kubernetes {
            yaml """
                apiVersion: v1
                kind: Pod
                spec:
                  containers:
                  - name: gradle
                    image: gradle
                    command:
                    - sleep
                    args:
                    - 99d
                    volumeMounts:
                    - name: shared-storage
                      mountPath: /mnt        
                  - name: kaniko
                    image: gcr.io/kaniko-project/executor:debug
                    command:
                    - sleep
                    args:
                    - 9999999
                    volumeMounts:
                    - name: shared-storage
                      mountPath: /mnt
                    - name: kaniko-secret
                      mountPath: /kaniko/.docker
                  restartPolicy: Never
                  volumes:
                  - name: shared-storage
                    persistentVolumeClaim:
                      claimName: jenkins-pv-claim
                  - name: kaniko-secret
                    secret:
                        secretName: dockercred
                        items:
                        - key: .dockerconfigjson
                          path: config.json
            """
        }
    }
    stages {
        stage('Checkout code AND run tests') {
            steps {
                git url: 'https://github.com/moisegermain/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
                container('gradle') {
                    sh """
                      cd Chapter08/sample1
                      chmod +x gradlew
                      ./gradlew test
                      """
                    // Conditional test execution
                    if (env.BRANCH_NAME == 'main') {
                        sh './gradlew codeCoverage'
                    }
                }
            }
        }
    }
    post {
        success {
            script {
                if (env.BRANCH_NAME == 'feature') {
                    echo "Create container repository/calculator-feature:0.1"
                    container('kaniko') {
                        sh """
                        # Commands to build and push the container image for feature branch
                        """
                    }
                } else if (env.BRANCH_NAME == 'main') {
                    echo "Create container repository/calculator:1.0"
                    container('kaniko') {
                        sh """
                        # Commands to build and push the container image for main branch
                        """
                    }
                }
                // No container is built for the 'playground' branch
            }
        }
    }
}
